ingredients: [
    { name: "Bananas", category: "Fruits" },
    { name: "Apples", category: "Fruits" },
    { name: "Oranges", category: "Fruits" },
    { name: "Strawberries", category: "Fruits" },
    { name: "Grapes", category: "Fruits" },
    { name: "Blueberries", category: "Fruits" },
    { name: "Raspberries", category: "Fruits" },
    { name: "Lemons", category: "Fruits" },
    { name: "Limes", category: "Fruits" },
    { name: "Avocados", category: "Fruits" },
    { name: "Tomatoes", category: "Vegetables" },
    { name: "Carrots", category: "Vegetables" },
    { name: "Potatoes", category: "Vegetables" },
    { name: "Onions", category: "Vegetables" },
    { name: "Garlic", category: "Vegetables" },
    { name: "Bell Peppers", category: "Vegetables" },
    { name: "Spinach", category: "Vegetables" },
    { name: "Broccoli", category: "Vegetables" },
    { name: "Cauliflower", category: "Vegetables" },
    { name: "Cucumbers", category: "Vegetables" },
    { name: "Lettuce", category: "Vegetables" },
    { name: "Zucchini", category: "Vegetables" },
    { name: "Mushrooms", category: "Vegetables" },
    { name: "Green Beans", category: "Vegetables" },
    { name: "Asparagus", category: "Vegetables" },
    { name: "Eggs", category: "Dairy" },
    { name: "Milk", category: "Dairy" },
    { name: "Cheese", category: "Dairy" },
    { name: "Butter", category: "Dairy" },
    { name: "Yogurt", category: "Dairy" },
    { name: "Cream", category: "Dairy" },
    { name: "Sour Cream", category: "Dairy" },
    { name: "Bread", category: "Bakery" },
    { name: "Bagels", category: "Bakery" },
    { name: "Croissants", category: "Bakery" },
    { name: "Tortillas", category: "Bakery" },
    { name: "Rice", category: "Grains" },
    { name: "Pasta", category: "Grains" },
    { name: "Quinoa", category: "Grains" },
    { name: "Oats", category: "Grains" },
    { name: "Chicken Breast", category: "Meat" },
    { name: "Ground Beef", category: "Meat" },
    { name: "Bacon", category: "Meat" },
    { name: "Sausage", category: "Meat" },
    { name: "Pork Chops", category: "Meat" },
    { name: "Steak", category: "Meat" },
    { name: "Salmon", category: "Seafood" },
    { name: "Shrimp", category: "Seafood" },
    { name: "Tilapia", category: "Seafood" },
    { name: "Tuna", category: "Seafood" },
    { name: "Cod", category: "Seafood" },
    { name: "Cereal", category: "Cereals" },
    { name: "Granola", category: "Cereals" },
    { name: "Flour", category: "Baking" },
    { name: "Sugar", category: "Baking" },
    { name: "Baking Powder", category: "Baking" },
    { name: "Baking Soda", category: "Baking" },
    { name: "Honey", category: "Baking" },
    { name: "Olive Oil", category: "Oils" },
    { name: "Vegetable Oil", category: "Oils" },
    { name: "Butter", category: "Oils" },
    { name: "Peanut Butter", category: "Condiments" },
    { name: "Jam", category: "Condiments" },
    { name: "Ketchup", category: "Condiments" },
    { name: "Mustard", category: "Condiments" },
    { name: "Mayonnaise", category: "Condiments" },
    { name: "Soy Sauce", category: "Condiments" },
    { name: "Hot Sauce", category: "Condiments" },
    { name: "Salt", category: "Spices" },
    { name: "Pepper", category: "Spices" },
    { name: "Cinnamon", category: "Spices" },
    { name: "Chili Powder", category: "Spices" },
    { name: "Garlic Powder", category: "Spices" },
    { name: "Paprika", category: "Spices" },
    { name: "Cumin", category: "Spices" },
    { name: "Basil", category: "Spices" },
    { name: "Oregano", category: "Spices" },
    { name: "Thyme", category: "Spices" },
    { name: "Parsley", category: "Spices" },
    { name: "Vinegar", category: "Condiments" },
    { name: "Soy Milk", category: "Dairy Alternatives" },
    { name: "Almond Milk", category: "Dairy Alternatives" },
    { name: "Coconut Milk", category: "Dairy Alternatives" },
    { name: "Tofu", category: "Vegetarian" },
    { name: "Tempeh", category: "Vegetarian" },
    { name: "Lentils", category: "Vegetarian" },
    { name: "Chickpeas", category: "Vegetarian" },
    { name: "Black Beans", category: "Vegetarian" },
    { name: "Kidney Beans", category: "Vegetarian" },
    { name: "Chips", category: "Snacks" },
    { name: "Crackers", category: "Snacks" },
    { name: "Popcorn", category: "Snacks" },
    { name: "Cookies", category: "Snacks" },
    { name: "Ice Cream", category: "Frozen" },
    { name: "Frozen Pizza", category: "Frozen" },
    { name: "Frozen Vegetables", category: "Frozen" },
    { name: "Frozen Fruit", category: "Frozen" },
    { name: "Orange Juice", category: "Beverages" },
    { name: "Apple Juice", category: "Beverages" },
    { name: "Soda", category: "Beverages" },
    { name: "Coffee", category: "Beverages" },
    { name: "Tea", category: "Beverages" },
    { name: "Beer", category: "Alcohol" },
    { name: "Wine", category: "Alcohol" }
]

